export const QUESTIONS = [
  {
    id: 'app_identity',
    alwaysShow: true,
    type: 'text_fields',
    title: 'What are you building?',
    subtitle: 'Give your app a name and reference a product that looks or works like what you have in mind. This single reference saves dozens of follow-up questions.',
    tag: null,
    fields: [
      { key: 'app_name',    label: 'App name',          type: 'text', placeholder: 'e.g. ShiftSync, BudgetPal, TaskMate', required: true },
      { key: 'similar_app', label: 'Similar app or URL', type: 'text', placeholder: 'e.g. https://trello.com  or  "like Airbnb but for parking"', optional: true },
    ],
    extraTextarea: {
      key: 'app_description',
      label: 'Describe your idea in plain words',
      optional: true,
      placeholder: 'Tell us what the app does, who uses it, and what problem it solves. No technical language needed.',
    },
  },
  {
    id: 'detail_level',
    alwaysShow: true,
    type: 'single',
    title: 'How much detail can you share right now?',
    subtitle: 'Your answer shapes the length of this survey. Honest is best — if you have rough ideas, Claude will fill in the gaps and state its assumptions clearly.',
    tag: 'Calibration — adjusts survey length',
    options: [
      { value: 'rough',    label: 'Just a rough idea',           desc: 'I know the problem but have not thought through the details. Let Claude fill in the gaps.' },
      { value: 'some',     label: 'I have thought about it',     desc: 'I have a clear vision in my head but have not written it down yet.' },
      { value: 'detailed', label: 'I have detailed requirements', desc: 'I have documents, wireframes, or a written spec I can upload.' },
    ],
    hasOther: true,
  },
  {
    id: 'app_type',
    alwaysShow: true,
    type: 'single',
    title: 'What kind of app is this?',
    subtitle: 'Choose the platform your users will primarily use.',
    tag: null,
    options: [
      { value: 'web',      label: 'Web app',        desc: 'Runs in a browser — desktop or laptop' },
      { value: 'mobile',   label: 'Mobile app',     desc: 'iOS and/or Android native app' },
      { value: 'both',     label: 'Web and mobile', desc: 'Users can use it from any device' },
      { value: 'internal', label: 'Internal tool',  desc: 'For your own team only, not the public' },
    ],
    hasOther: true,
  },
  {
    id: 'target_users',
    alwaysShow: true,
    type: 'multiple',
    title: 'Who are your target users?',
    subtitle: 'Select all that apply.',
    tag: null,
    options: [
      { value: 'consumers',   label: 'General public (B2C)',        desc: 'Everyday people using the app for personal needs' },
      { value: 'businesses',  label: 'Businesses (B2B)',            desc: 'Companies paying to use it for their operations' },
      { value: 'internal',    label: 'Internal team only',          desc: 'Your own employees or colleagues' },
      { value: 'marketplace', label: 'Both sides of a marketplace', desc: 'e.g. buyers and sellers, drivers and passengers' },
    ],
    hasOther: true,
  },
  {
    id: 'problem',
    alwaysShow: true,
    type: 'multiple',
    title: 'What problem does your app solve?',
    subtitle: 'Select all that apply. A focused problem is better than many.',
    tag: null,
    options: [
      { value: 'saves_time',      label: 'Saves time on a repetitive task',           desc: 'Something people do over and over that could be automated' },
      { value: 'connects',        label: 'Connects people who need each other',        desc: 'Matching, marketplace, or networking' },
      { value: 'replaces_manual', label: 'Replaces a paper or manual process',        desc: 'Digitising spreadsheets, forms, or pen-and-paper workflows' },
      { value: 'affordable',      label: 'Makes something expensive more accessible', desc: 'Democratising a service currently out of reach' },
      { value: 'track',           label: 'Helps people track or manage information',  desc: 'Dashboards, inventory, records, analytics' },
    ],
    hasOther: true,
  },
  {
    id: 'current_solution',
    alwaysShow: true,
    type: 'single',
    title: 'How do people solve this problem today?',
    subtitle: 'Understanding the status quo defines what "better" looks like.',
    tag: null,
    options: [
      { value: 'spreadsheets', label: 'Spreadsheets or documents',        desc: 'Excel, Google Sheets, Word, paper forms' },
      { value: 'nothing',      label: 'No good solution exists',          desc: 'People live with the pain or work around it' },
      { value: 'competitor',   label: 'A competitor product',             desc: 'Name it in the Other field below' },
      { value: 'cobbled',      label: 'Multiple tools stitched together', desc: 'Using 3-5 apps to get one job done' },
      { value: 'manual',       label: 'Done manually or physically',      desc: 'By phone, in person, or with human effort each time' },
    ],
    hasOther: true,
  },
  {
    id: 'core_action',
    alwaysShow: true,
    type: 'single',
    title: 'What is the one core thing users come to your app to do?',
    subtitle: 'If your app could only do one thing, what would it be?',
    tag: null,
    options: [
      { value: 'search',      label: 'Search and find something',   desc: 'Discover products, services, people, or information' },
      { value: 'book',        label: 'Book or schedule something',  desc: 'Reserve time slots, manage calendars or shifts' },
      { value: 'buy_sell',    label: 'Buy or sell something',       desc: 'E-commerce, marketplace, or transactions' },
      { value: 'create',      label: 'Create and manage content',   desc: 'Write, upload, organise, or publish things' },
      { value: 'communicate', label: 'Connect and communicate',     desc: 'Message, collaborate, or network with others' },
      { value: 'track',       label: 'Track and monitor something', desc: 'Dashboard, analytics, inventory, or reporting' },
    ],
    hasOther: true,
  },
  {
    id: 'key_screens',
    minLevel: 'some',
    type: 'multiple',
    title: 'Which screens or pages should the app have?',
    subtitle: 'Select everything a user would see. You can adjust later.',
    tag: null,
    options: [
      { value: 'login',         label: 'Login / Register' },
      { value: 'dashboard',     label: 'Home / Dashboard' },
      { value: 'search',        label: 'Search / Browse / Explore' },
      { value: 'profile',       label: 'Profile / Account settings' },
      { value: 'messaging',     label: 'Messaging / Chat' },
      { value: 'booking',       label: 'Booking / Scheduling / Calendar' },
      { value: 'payment',       label: 'Payment / Checkout' },
      { value: 'admin',         label: 'Admin panel' },
      { value: 'notifications', label: 'Notifications feed' },
      { value: 'reporting',     label: 'Reports / Analytics' },
    ],
    hasOther: true,
  },
  {
    id: 'must_have_features',
    minLevel: 'some',
    type: 'multiple',
    title: 'Which features are essential for the first version?',
    subtitle: 'Be strict — only select what is truly required on day one.',
    tag: null,
    options: [
      { value: 'auth',          label: 'User login and registration' },
      { value: 'search_filter', label: 'Search and filtering' },
      { value: 'notifications', label: 'Email or push notifications' },
      { value: 'payments',      label: 'Payments (Stripe, etc.)' },
      { value: 'file_upload',   label: 'File or image uploads' },
      { value: 'chat',          label: 'Chat or messaging' },
      { value: 'admin_panel',   label: 'Admin panel (manage users/content)' },
      { value: 'analytics',     label: 'Reporting or analytics dashboard' },
      { value: 'integrations',  label: 'Third-party integrations (Maps, CRM, etc.)' },
    ],
    hasOther: true,
  },
  {
    id: 'look_feel',
    minLevel: 'some',
    type: 'multiple',
    title: 'What look and feel do you want?',
    subtitle: 'Select all that match the vibe you are going for.',
    tag: null,
    options: [
      { value: 'minimal',      label: 'Clean and minimal',           desc: 'Like Notion, Linear, or Apple' },
      { value: 'professional', label: 'Professional and corporate',  desc: 'Like Salesforce, Monday, or Workday' },
      { value: 'colorful',     label: 'Colorful and approachable',   desc: 'Like Duolingo, Canva, or Figma' },
      { value: 'dark',         label: 'Dark mode / developer style', desc: 'Like GitHub, Vercel, or VS Code' },
      { value: 'marketplace',  label: 'Marketplace / consumer style', desc: 'Like Airbnb, Etsy, or Booking.com' },
    ],
    hasOther: true,
  },
  {
    id: 'success_metric',
    alwaysShow: true,
    type: 'single',
    title: 'What does success look like in 6 months?',
    subtitle: 'Pick the one metric you would use to know this worked.',
    tag: null,
    options: [
      { value: 'users',      label: 'Number of users who sign up' },
      { value: 'revenue',    label: 'Revenue generated' },
      { value: 'tasks',      label: 'Number of tasks or bookings completed' },
      { value: 'validation', label: 'Validated the idea (real users tried it)' },
      { value: 'retention',  label: 'Users keep coming back (retention / daily active users)' },
    ],
    hasOther: true,
  },
  {
    id: 'timeline',
    alwaysShow: true,
    type: 'single',
    title: 'When do you need a working version?',
    subtitle: 'A tighter deadline means a smaller first version. Be realistic.',
    tag: null,
    options: [
      { value: '2weeks',   label: '1-2 weeks',          desc: 'Micro-MVP: the bare minimum to show someone' },
      { value: '1month',   label: '1 month',            desc: 'Small MVP: core flow working end-to-end' },
      { value: '3months',  label: '2-3 months',         desc: 'Solid MVP: polished enough for early customers' },
      { value: '6months',  label: '6 months or more',   desc: 'Full product: multiple features, production-ready' },
      { value: 'flexible', label: 'No strict deadline', desc: 'Getting it right matters more than speed' },
    ],
    hasOther: true,
  },
  {
    id: 'budget',
    alwaysShow: true,
    type: 'single',
    title: 'What is your monthly infrastructure budget?',
    subtitle: 'This covers hosting, database, and services like email or payments. Does not include Claude usage.',
    tag: null,
    options: [
      { value: 'free',   label: 'Free / under $20/month', desc: 'Startup mode — use free tiers wherever possible' },
      { value: 'small',  label: '$20-$100/month',         desc: 'Early stage — some paid services are OK' },
      { value: 'medium', label: '$100-$500/month',        desc: 'Growth stage — quality infrastructure' },
      { value: 'large',  label: '$500+/month',            desc: 'Scale — whatever is needed to serve users well' },
      { value: 'unsure', label: 'Not sure yet',           desc: 'Claude will recommend based on scope' },
    ],
    hasOther: true,
  },
  {
    id: 'existing_docs',
    minLevel: 'detailed',
    type: 'multiple_upload',
    title: 'Do you have any existing documents or designs to share?',
    subtitle: 'Upload anything useful. Claude will use these directly instead of guessing.',
    tag: null,
    options: [
      { value: 'wireframes',  label: 'Wireframes or mockups',                canUpload: true },
      { value: 'spec',        label: 'Written spec or requirements doc',      canUpload: true },
      { value: 'screenshots', label: 'Competitor or inspiration screenshots', canUpload: true },
      { value: 'brand',       label: 'Logo or brand guidelines',              canUpload: true },
      { value: 'none',        label: 'Starting from scratch — no documents' },
    ],
    hasOther: true,
  },
  {
    id: 'anything_else',
    alwaysShow: true,
    type: 'textarea_only',
    title: 'Anything else Claude should know?',
    subtitle: 'Regulations, hard constraints, things you definitely do not want, personal context — anything goes.',
    tag: null,
    placeholder: 'e.g. "Must comply with HIPAA" or "Had a failed attempt before" or "Design must feel premium for enterprise clients"',
  },
]

const LEVEL_ORDER = { rough: 0, some: 1, detailed: 2 }

export function visibleQuestions(detailLevel) {
  const level = detailLevel || 'rough'
  const order = LEVEL_ORDER[level] ?? 0
  return QUESTIONS.filter(q => {
    if (q.alwaysShow) return true
    if (!q.minLevel) return false
    return order >= (LEVEL_ORDER[q.minLevel] ?? 0)
  })
}
